"""Displacement-discontinuity toolkit shared by both lithology notebooks.

104 functions and 15 constants that were
previously duplicated verbatim in each notebook, grouped into themed views:

  angles      Angle wrapping, axial statistics and orientation blending.
  elasticity  Orthotropic constitutive relations, stresses and strains.
  failure     Failure criteria, weak-band weighting and contact/platen models.
  figures     Publication figure helpers.
  fitting     Model fitting, metrics and measured-data comparison.
  grids       Disc grids, masks, polylines and segment geometry.
  io          Field archive read/write, path discovery and solver binding.
  smoothing   Smoothing, kernel density, bootstrap bands and curve collapse.
  solver      Finite-difference operators, tractions and the energy-guided stepper.

Every name is also importable from this package root.
"""

from . import angles, elasticity, failure, figures, fitting, grids, io, smoothing, solver  # noqa: F401
from ._toolkit import (  # noqa: F401
    # angles
    angle_axis,
    axial_stats_from_delta,
    axis_angle,
    deviation_arrays,
    trough_angle_from_xi,
    wrap_axis_angle,
    # elasticity
    band_open_factor_from_sigma_n,
    compute_sample_stresses,
    modulus_to_Pa_from_csv,
    nominal_splitting_stress,
    orthotropic_roots_p,
    principal_from_components,
    principal_strain_and_angle,
    principal_stresses_and_angle,
    q_matrix_plane_stress_orthotropic,
    required_load_for_target_sigma_t,
    sigma1_plus,
    splitting_stress_pa,
    strain_energy_density_ortho_plane_stress_material,
    strains_from_stress_TIsotropic,
    surrogate_tensile_weight,
    tensile_stress_from_sigma1_theta,
    transform_Q_to_angle,
    # failure
    _safe_compute_psi_pref,
    _safe_wp_weight,
    build_psi_pref_field,
    compute_wp_weight_img,
    disk_failure_stats_all_points,
    evaluate_failure_mode,
    evaluate_failure_mode_mohr_coulomb_constant,
    get_anisotropy_ratio,
    get_material_axes,
    hertz_contact_halfwidth,
    platen_weight,
    surrogate_conf_weight,
    surrogate_energy_proxy,
    surrogate_wp_weight,
    # figures
    _get_marker,
    _label_full,
    _label_short,
    _make_all_combined_plots,
    _mode_to_code_img,
    apply_plot_style,
    make_figure1,
    make_figure2,
    plot_direction_circle,
    set_pub_style,
    # fitting
    choose_smallest_near_peak,
    compare_with_measured_data,
    fit_coeffs_collocation,
    generate_random_props,
    get_row_material_props,
    pooled_equal_weight_abs_delta,
    print_material_parameters,
    summarize_distribution,
    summarize_modes,
    # grids
    _grid_axes,
    _grid_axes_from_mesh,
    _grid_cell_area,
    _img_from_mask,
    _polyline_length,
    _thin_points_for_glyphs,
    build_segments_from_axis,
    clip_to_disk,
    create_grid_mesh,
    create_structured_grid,
    create_triangular_mesh_in_disk,
    downsample_mask,
    make_segments,
    reconstruct_grid,
    reconstruct_grid_and_mask,
    sample_line,
    snap_path_to_platen_arcs,
    valid_mask_from_fields,
    # io
    _search_dirs,
    bind_sif_hooks,
    sif_hooks,
    get_first_col,
    import_or_load_solver,
    load_module_from_path,
    load_sample_fields_physical,
    npz_path_for_sample,
    output_prefix_from_records,
    replot_from_csvs,
    sanitize_name,
    save_all_energy_plot,
    save_all_paths_plot,
    save_all_ratio_plot,
    save_full_fields_npz,
    save_sample_fields_npz,
    validate_solver_api,
    # smoothing
    compute_poly_ci,
    gaussian_kde_manual,
    gaussian_smooth_1d,
    mean_profile_midband,
    nan_box_blur,
    nearest_mean,
    robust_bandwidth,
    # solver
    _adaptive_N_outer,
    _adaptive_kink_n,
    _normalize_rock_name,
    bilinear_sample_scalar,
    bilinear_scalar,
    check_force_equilibrium,
    integrate_line_force,
    traction_from_coeffs_on_boundary,
    # constants
    PLOT_STYLE,
    ROCK_ANISO_RATIO,
    TICK_PARAMS,
    TOL_VIBRANT,
    _ANGLE_MARKERS,
    _COLORS,
    bd,
    boundary_exclude_frac,
    cap_exclude_frac,
    density,
    length_exponent,
    max_seg_frac,
    min_show_frac,
    platen_smooth,
    tick_params,
)

__all__ = [
    "_adaptive_N_outer",
    "_adaptive_kink_n",
    "_get_marker",
    "_grid_axes",
    "_grid_axes_from_mesh",
    "_grid_cell_area",
    "_img_from_mask",
    "_label_full",
    "_label_short",
    "_make_all_combined_plots",
    "_mode_to_code_img",
    "_normalize_rock_name",
    "_polyline_length",
    "_safe_compute_psi_pref",
    "_safe_wp_weight",
    "_search_dirs",
    "_thin_points_for_glyphs",
    "angle_axis",
    "apply_plot_style",
    "axial_stats_from_delta",
    "axis_angle",
    "band_open_factor_from_sigma_n",
    "bilinear_sample_scalar",
    "bilinear_scalar",
    "bind_sif_hooks",
    "sif_hooks",
    "build_psi_pref_field",
    "build_segments_from_axis",
    "check_force_equilibrium",
    "choose_smallest_near_peak",
    "clip_to_disk",
    "compare_with_measured_data",
    "compute_poly_ci",
    "compute_sample_stresses",
    "compute_wp_weight_img",
    "create_grid_mesh",
    "create_structured_grid",
    "create_triangular_mesh_in_disk",
    "deviation_arrays",
    "disk_failure_stats_all_points",
    "downsample_mask",
    "evaluate_failure_mode",
    "evaluate_failure_mode_mohr_coulomb_constant",
    "fit_coeffs_collocation",
    "gaussian_kde_manual",
    "gaussian_smooth_1d",
    "generate_random_props",
    "get_anisotropy_ratio",
    "get_material_axes",
    "get_first_col",
    "get_row_material_props",
    "hertz_contact_halfwidth",
    "import_or_load_solver",
    "integrate_line_force",
    "load_module_from_path",
    "load_sample_fields_physical",
    "make_figure1",
    "make_figure2",
    "make_segments",
    "mean_profile_midband",
    "modulus_to_Pa_from_csv",
    "nan_box_blur",
    "nearest_mean",
    "nominal_splitting_stress",
    "npz_path_for_sample",
    "orthotropic_roots_p",
    "output_prefix_from_records",
    "platen_weight",
    "plot_direction_circle",
    "pooled_equal_weight_abs_delta",
    "principal_from_components",
    "principal_strain_and_angle",
    "principal_stresses_and_angle",
    "print_material_parameters",
    "q_matrix_plane_stress_orthotropic",
    "reconstruct_grid",
    "reconstruct_grid_and_mask",
    "replot_from_csvs",
    "required_load_for_target_sigma_t",
    "robust_bandwidth",
    "sample_line",
    "sanitize_name",
    "save_all_energy_plot",
    "save_all_paths_plot",
    "save_all_ratio_plot",
    "save_full_fields_npz",
    "save_sample_fields_npz",
    "set_pub_style",
    "sigma1_plus",
    "snap_path_to_platen_arcs",
    "splitting_stress_pa",
    "strain_energy_density_ortho_plane_stress_material",
    "strains_from_stress_TIsotropic",
    "summarize_distribution",
    "summarize_modes",
    "surrogate_conf_weight",
    "surrogate_energy_proxy",
    "surrogate_tensile_weight",
    "surrogate_wp_weight",
    "tensile_stress_from_sigma1_theta",
    "traction_from_coeffs_on_boundary",
    "transform_Q_to_angle",
    "trough_angle_from_xi",
    "valid_mask_from_fields",
    "validate_solver_api",
    "wrap_axis_angle",
    "PLOT_STYLE",
    "ROCK_ANISO_RATIO",
    "TICK_PARAMS",
    "TOL_VIBRANT",
    "_ANGLE_MARKERS",
    "_COLORS",
    "bd",
    "boundary_exclude_frac",
    "cap_exclude_frac",
    "density",
    "length_exponent",
    "max_seg_frac",
    "min_show_frac",
    "platen_smooth",
    "tick_params",
]
