#!/usr/bin/env python3
"""Report which manuscript-cited figures the notebooks regenerated, and which drifted.

Every figure the manuscript includes should be produced by the pipeline that
claims to produce it. Two things go wrong quietly:

* a figure stops being regenerated -- the code that wrote it broke, or moved --
  and the copy in ``manuscript/`` silently becomes the output of an older model;
* a figure is regenerated somewhere in the tree but never copied to
  ``manuscript/``, so the paper keeps embedding the stale one.

By default nothing is copied or overwritten: replacing a figure the paper
embeds is an editorial decision, so the report is the whole output.

``--sync`` opts into the copy. It brings ``manuscript/`` up to date with the
generated figures, which is what a full regeneration needs in order for the
paper to build again. It only ever copies *into* ``manuscript/``, and only for
figures the pipeline actually produces; anything with no generated counterpart
is left alone, because those are the hand-made drawings and photographs that
nothing in this repository can recreate.

    python scripts/check_manuscript_figures.py            # report only
    python scripts/check_manuscript_figures.py --sync     # and copy them in
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from datetime import datetime
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from tools import output_dirs  # noqa: E402
DEFAULT_TEX = REPO / "manuscript" / "manscript_revision_001.tex"

#: Where generated figures land, in the order they should be preferred.
SEARCH = [output_dirs.FIGURE_DIR, output_dirs.TABLE_DIR,
          # The k_max sweep still writes to the repository root, so the root
          # has to be searched too or the sync silently reports its figure as
          # produced by nothing.
          "."]

INCLUDE = re.compile(r"includegraphics\[[^\]]*\]\{([\w./-]+)\}")


def digest(path):
    return hashlib.sha1(path.read_bytes()).hexdigest()[:12]


def cited(tex_path):
    text = tex_path.read_text(encoding="utf-8")
    names = sorted({m.group(1) for m in INCLUDE.finditer(text)})
    # \includegraphics is often written without the extension
    return [n if Path(n).suffix else n + ".pdf" for n in names]


def find_generated(name):
    """Every generated copy of a figure, newest first."""
    hits = []
    for folder in SEARCH:
        p = REPO / folder / Path(name).name
        if p.exists():
            hits.append(p)
    return sorted(hits, key=lambda p: p.stat().st_mtime, reverse=True)


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--tex", type=Path, default=DEFAULT_TEX)
    ap.add_argument("--since", type=str, default=None,
                    help="ISO date; flag manuscript copies older than this")
    ap.add_argument("--sync", action="store_true",
                    help="copy generated figures into manuscript/ (see module docstring)")
    args = ap.parse_args(argv)

    cutoff = datetime.fromisoformat(args.since).timestamp() if args.since else None

    missing, stale, orphan, ok = [], [], [], []
    for name in cited(args.tex):
        in_manuscript = REPO / "manuscript" / Path(name).name
        generated = find_generated(name)

        if not in_manuscript.exists() and not generated:
            missing.append(name)
            continue
        if not generated:
            orphan.append((name, in_manuscript))
            continue
        newest = generated[0]
        if not in_manuscript.exists():
            stale.append((name, newest, "not in manuscript/"))
        elif digest(in_manuscript) != digest(newest):
            age = datetime.fromtimestamp(in_manuscript.stat().st_mtime).date()
            stale.append((name, newest, f"differs from {newest.parent.name}/, "
                                        f"manuscript copy dated {age}"))
        elif cutoff and newest.stat().st_mtime < cutoff:
            stale.append((name, newest, "not regenerated in this run"))
        else:
            ok.append(name)

    print(f"{len(ok)} up to date, {len(stale)} differ, "
          f"{len(orphan)} not generated by the pipeline, {len(missing)} missing\n")

    if stale and args.sync:
        import shutil
        dest_dir = REPO / "manuscript"
        print(f"Copying {len(stale)} generated figures into manuscript/:")
        for name, newest, why in stale:
            dest = dest_dir / Path(name).name
            shutil.copy2(newest, dest)
            print(f"  {Path(name).name:52s} <- {newest.parent.name}/")
        print()
    elif stale:
        print("Differ from the generated version "
              "(nothing copied; pass --sync to copy them in):")
        for name, newest, why in stale:
            print(f"  {name}\n      {newest.relative_to(REPO)}  [{why}]")
        print()
    if orphan:
        print("In manuscript/ but produced by nothing in the tree:")
        for name, path in orphan:
            print(f"  {name}  ({path.relative_to(REPO)})")
        print()
    if missing:
        print("Cited but found nowhere:")
        for name in missing:
            print(f"  {name}")

    return 1 if (missing or stale) else 0


if __name__ == "__main__":
    sys.exit(main())
