#!/usr/bin/env python3
"""Supplementary table and figure testing the G/Gc profile claims.

Mode-I dominance was inferred from the *shape* of the low-angle G/Gc profiles:
monotonic increase at low foliation angles, oscillation only at intermediate
angles. Shape claims are measurable, so this script measures them across all 14
specimens and writes the evidence out as supplementary material.

    python scripts/make_fig20_supplement.py

Writes
  outputs/tables/fig20_GGc_profile_metrics.csv    per-specimen measurements
  outputs/tables/fig20_GGc_band_summary.csv       band means, the low-vs-intermediate test
  manuscript/tables/table_S_fig20_GGc.txt         supplementary table
  manuscript/fig_S_GGc_monotonicity.pdf    supplementary figure (+ .png)
"""
from __future__ import annotations

from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from tools import fracture_energy as fe          # noqa: E402
from tools import output_dirs  # noqa: E402
from tools.plot_style import apply_plot_style    # noqa: E402

REPO = Path(__file__).resolve().parents[1]
BAND_COLOR = {"low (0-30 deg)": "#0072B2",
              "intermediate (45-60 deg)": "#E69F00",
              "high (75-90 deg)": "#009E73"}
BAND_SHORT = {"low (0-30 deg)": "low, 0\u201330\u00b0",
              "intermediate (45-60 deg)": "intermediate, 45\u201360\u00b0",
              "high (75-90 deg)": "high, 75\u201390\u00b0"}
#: LaTeX spellings for the table, where -- and \circ are real markup.
BAND_TEX = {"low (0-30 deg)": r"low, $0$--$30^\circ$",
            "intermediate (45-60 deg)": r"intermediate, $45$--$60^\circ$",
            "high (75-90 deg)": r"high, $75$--$90^\circ$"}



ASYMMETRIC = "asymmetric"
APPROX_SYMMETRIC = r"approx.\ symmetric"

def latex_table(df, band, v) -> str:
    """Per-specimen measurements and the band comparison, as two blocks.

    The columns that are constant across every specimen (no profile is
    monotonic; no step falls below Gc) are stated once in the caption rather
    than repeated down a column, which is what let the table overrun the page.

    Returns the two tables separately. They were emitted as one block, which
    forced them adjacent in the supplement; the per-specimen table is first
    cited in the methods and the band table only in Section 4.10, so keeping
    them together put the supplement out of citation order. One block per
    table lets each sit where it is first referred to.
    """
    rows = "\n".join(
        f"{r['sample']:.0f} & {r['lithology']} & {r['angle_deg']:.0f} & "
        f"{r['n_steps']:.0f} & {r['reversal_fraction']:.2f} & "
        f"{r['cv']:.2f} & {r['min_G_over_Gc_energy']:.3f} & {r['shear_fraction']:.2f} \\\\"
        for _, r in df.iterrows())

    brows = "\n".join(
        f"{BAND_TEX[r['band']]} & {r['n_profiles']:.0f} & {r['n_monotonic']:.0f} & "
        f"{r['mean_reversal_fraction']:.2f} & {r['mean_CV']:.2f} & "
        f"{r['mean_shear_fraction']:.2f} \\\\"
        for _, r in band.iterrows())

    return rf"""% Generated by scripts/make_fig20_supplement.py; do not edit by hand.
\begin{{table}}[htbp]
\centering
\small
\caption{{\rev{{Quantitative test of the Fig.~\ref{{fig:ratio}} $G/G_c$ claims,
per specimen. ``Rev.\ frac.'' is the fraction of propagation steps at which
$G/G_c$ decreases; CV is the coefficient of variation of $G/G_c$ along the path
(sample standard deviation), an oscillation amplitude independent of path
length; ``Shear frac.'' is the fraction of steps with
$|K_{{II}}|/|K_{{I}}| > {fe.SHEAR_RATIO_THRESHOLD}$. Two results are constant
across all fourteen specimens and are therefore stated here rather than carried
as columns: no profile is strictly monotonic at any orientation, and $G$ never
falls below $G_c$ on any energy-driven step, the smallest such value over the
whole dataset being {v['min_G_over_Gc_energy']:.3f}. Steps are of two kinds. An
energy-driven step is chosen by maximizing $G-G_c$ over admissible directions;
where no direction clears $G_c$ the path instead follows the
preferred-orientation field, and such steps are sub-critical by construction
rather than by measurement. They are a majority of the path
({v['phys_fraction_mean'] * 100:.0f}\% of steps on average), so arrest is judged on the
energy-driven steps alone, where the question is well posed. The $\min G/G_c$ column
below is therefore the minimum over the energy-driven steps.}}}}
\label{{tab:fig20_GGc}}
\begin{{tabular}}{{r l r r r r r r}}
\toprule
Spec. & Lithology & $\alpha$ (deg) & Steps & Rev.\ frac. & CV &
$\min G/G_c$ & Shear frac. \\
\midrule
{rows}
\bottomrule
\end{{tabular}}
\end{{table}}
""", rf"""% Generated by scripts/make_fig20_supplement.py; do not edit by hand.
\begin{{table}}[htbp]
\centering
\small
\caption{{\rev{{Angle-band means of the same measurements. If oscillation were
confined to intermediate fabric angles, the low-angle band would show a markedly
smaller CV; it does not, and the ratio of the low-angle to intermediate-angle
mean CV is {v['CV_ratio_low_over_intermediate']:.2f}. Monotonic profiles number
zero in every band.}}}}
\label{{tab:fig20_bands}}
\begin{{tabular}}{{l r r r r r}}
\toprule
Band & Profiles & Monotonic & Rev.\ frac. & CV & Shear frac. \\
\midrule
{brows}
\bottomrule
\end{{tabular}}

\vspace{{2mm}}
\footnotesize
\rev{{Every run carries $G_{{c0}}=1.0$, so $G/G_c$ is a relative along-path
measure rather than a margin against a measured toughness.}}
\end{{table}}
"""


def make_figure(df, band, out):
    apply_plot_style()
    fig, axes = plt.subplots(1, 3, figsize=(15, 4.6),
                             gridspec_kw=dict(width_ratios=[1.5, 1, 1]))

    # (a) every profile, so the reader can see reversals at all angles
    ax = axes[0]
    for _, r in df.iterrows():
        d = fe.load_profile(r["sample"])
        ratio = (d["G"] / d["Gc"]).to_numpy(float)
        x = np.linspace(0, 1, ratio.size)
        ax.plot(x, ratio, lw=1.1, alpha=0.85, color=BAND_COLOR[r["band"]])
    ax.axhline(1.0, color="0.25", ls="--", lw=1.4, zorder=5)
    ax.text(0.015, 1.02, r"$G=G_c$", transform=ax.get_yaxis_transform(),
            fontsize=11, color="0.25", va="bottom")
    ax.set_yscale("log")
    ax.set_xlabel("Normalised propagation step")
    ax.set_ylabel(r"$G/G_c$")
    ax.set_title("(a) All 14 profiles", loc="left")
    for b, c in BAND_COLOR.items():
        ax.plot([], [], color=c, lw=2, label=BAND_SHORT[b])
    ax.legend(frameon=False, loc="upper left", fontsize=10)

    # (b) reversal fraction per specimen — monotonicity would be zero
    ax = axes[1]
    xs = np.arange(len(df))
    ax.bar(xs, df["reversal_fraction"], color=[BAND_COLOR[b] for b in df["band"]])
    ax.set_xticks(xs)
    ax.set_xticklabels([f"{a:.0f}" for a in df["angle_deg"]], fontsize=9)
    ax.set_xlabel(r"Foliation angle $\alpha$ (deg)")
    ax.set_ylabel("Fraction of steps that reverse")
    top = max(0.72, df["reversal_fraction"].max() * 1.45)
    ax.set_ylim(0, top)
    ax.axhline(0, color="0.2", lw=1.2)
    ax.set_title("(b) Monotonicity", loc="left")
    # the 14 specimens are 7 gneiss then 7 schist; say so rather than repeat 0-90
    split = int((df["lithology"] == df["lithology"].iloc[0]).sum()) - 0.5
    ax.axvline(split, color="0.45", lw=1.2, ls=":")
    for lo, hi, name in ((0, split, df["lithology"].iloc[0]),
                         (split, len(df) - 1, df["lithology"].iloc[-1])):
        ax.text((lo + hi) / 2, top * 0.99, name, ha="center", va="top",
                fontsize=10, color="0.3")
    ax.text(0.5, 0.87, "a monotonic profile would be zero everywhere",
            transform=ax.transAxes, ha="center", fontsize=10, color="0.3")

    # (c) oscillation amplitude by band — the low-vs-intermediate comparison
    ax = axes[2]
    bx = np.arange(len(band))
    ax.bar(bx, band["mean_CV"], color=[BAND_COLOR[b] for b in band["band"]], width=0.6)
    for i, v in enumerate(band["mean_CV"]):
        ax.text(i, v, f"{v:.2f}", ha="center", va="bottom", fontsize=11)
    ax.set_xticks(bx)
    ax.set_xticklabels(["low\n0-30", "interm.\n45-60", "high\n75-90"], fontsize=10)
    ax.set_xlabel("Foliation angle band (deg)")
    ax.set_ylabel(r"Mean CV of $G/G_c$")
    ax.set_ylim(0, band["mean_CV"].max() * 1.35)
    ax.set_title("(c) Oscillation amplitude", loc="left")
    ax.text(0.5, 0.88, "bands are indistinguishable", transform=ax.transAxes,
            ha="center", fontsize=10, color="0.3")

    for a in axes:
        a.tick_params(which="major", direction="out", length=5, width=1.5)
        for s in a.spines.values():
            s.set_linewidth(1.5)

    fig.tight_layout()
    for ext in ("pdf", "png"):
        fig.savefig(f"{out}.{ext}", dpi=300, bbox_inches="tight")
    plt.close(fig)
    return [f"{out}.{ext}" for ext in ("pdf", "png")]


def main():
    df = fe.all_profiles()
    band = fe.band_summary(df)
    v = fe.verdict(df)

    output_dirs.tables()
    df.to_csv(REPO / output_dirs.TABLE_DIR / "fig20_GGc_profile_metrics.csv", index=False)
    band.to_csv(REPO / output_dirs.TABLE_DIR / "fig20_GGc_band_summary.csv", index=False)
    profiles_tex, bands_tex = latex_table(df, band, v)
    (REPO / "manuscript/tables/table_S_fig20_GGc.txt").write_text(
        profiles_tex, encoding="utf-8")
    (REPO / "manuscript/tables/table_S_fig20_bands.txt").write_text(
        bands_tex, encoding="utf-8")
    figs = make_figure(df, band, str(REPO / "manuscript/fig_S_GGc_monotonicity"))

    # The mirror-symmetry table is the other supplement this script owns. It was
    # defined below the __main__ guard and never called, so its table sat
    # frozen at whatever the last manual run produced.
    mirror_out = mirror_symmetry_table()

    print(f"profiles measured                : {v['n_profiles']}")
    print(f"strictly monotonic               : {v['n_monotonic']}  "
          f"(claim supported: {v['monotonic_claim_supported']})")
    print(f"CV low / intermediate            : {v['low_band_CV']:.3f} / "
          f"{v['intermediate_band_CV']:.3f}  "
          f"(ratio {v['CV_ratio_low_over_intermediate']:.3f})")
    print(f"oscillation confined to interm.  : "
          f"{v['oscillation_confined_to_intermediate']}")
    print(f"min G/Gc, steps below Gc         : {v['min_G_over_Gc']:.4f}, "
          f"{v['total_steps_below_Gc']}")
    print(f"mean shear fraction, low band    : "
          f"{v['mean_shear_fraction_low_band']:.3f}")
    print("\nwritten:")
    for p in [output_dirs.TABLE_DIR + "/fig20_GGc_profile_metrics.csv",
              output_dirs.TABLE_DIR + "/fig20_GGc_band_summary.csv",
              output_dirs.TABLE_DIR + "/displacement_mirror_symmetry.csv",
              "manuscript/tables/table_S_fig20_GGc.txt",
              "manuscript/tables/table_S_fig20_bands.txt",
              str(mirror_out)] + [Path(f).name for f in figs]:
        print("  ", p)
    return 0


def mirror_symmetry_table(out_path=None):
    """Supplementary table of the displacement mirror-symmetry indices.

    The machine-readable copy is written alongside the LaTeX table. It used to
    be written elsewhere, and once that other writer went away the CSV stopped
    being refreshed while this table kept tracking the data. The two then
    disagreed for a fortnight: the CSV still showed one specimen as having no
    cached displacement solution long after the cache existed, so anyone
    auditing the paper from ``outputs/tables/`` would have found a specimen
    missing that the manuscript correctly counted. Writing both here means the
    published table and the machine-readable record cannot drift apart again.
    """
    from tools import displacement_symmetry as ds

    df = ds.all_specimens()
    output_dirs.tables()
    csv_out = REPO / output_dirs.TABLE_DIR / "displacement_mirror_symmetry.csv"
    df.to_csv(csv_out, index=False)

    rows = []
    for _, r in df.iterrows():
        if r["status"] != "computed":
            rows.append(f"{r['sample']:.0f} & {r['lithology']} & "
                        f"{r['angle_deg']:.0f} & \\multicolumn{{4}}{{c}}{{"
                        f"no cached displacement solution}} \\\\")
            continue
        rows.append(
            f"{r['sample']:.0f} & {r['lithology']} & {r['angle_deg']:.0f} & "
            f"{r['u_antisymmetry_index']:.3f} & {r['v_symmetry_index']:.3f} & "
            f"{r['max_index']:.3f} & "
            # the backslash cannot live inside the f-string expression on <3.12
            f"{ASYMMETRIC if r['visibly_asymmetric'] else APPROX_SYMMETRIC} \\\\")
    body = "\n".join(rows)

    tex = rf"""% Generated by scripts/make_fig20_supplement.py; do not edit by hand.
\begin{{table}}[htbp]
\centering
\footnotesize
\caption{{\rev{{Mirror-symmetry indices of the displacement field about the
loading axis. Under an ideal mirror the horizontal component $u$ is
antisymmetric and the vertical component $v$ symmetric, so
$A_u = \lVert u(x)+u(-x)\rVert / 2\lVert u\rVert$ and
$A_v = \lVert v(x)-v(-x)\rVert / 2\lVert v\rVert$ are zero for a perfectly
mirror-symmetric field and bounded by one. Fields are classed as visibly
asymmetric when $\max(A_u,A_v)$ exceeds {ds.VISIBLE_ASYMMETRY:.2f}. Departures
are small at the fabric end members and large at intermediate orientations in
both lithologies, which is expected because an inclined fabric is itself not
mirror-symmetric about the loading axis.}}}}
\label{{tab:mirror_symmetry}}
\begin{{tabular}}{{r l r r r r l}}
\toprule
Spec. & Lithology & $\alpha$ (deg) & $A_u$ & $A_v$ & $\max(A_u,A_v)$ & Description \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    out = Path(out_path or (REPO / "manuscript/tables/table_S_mirror_symmetry.txt"))
    out.write_text(tex, encoding="utf-8")
    return out


if __name__ == "__main__":
    raise SystemExit(main())
