#!/usr/bin/env python3
"""Per-orientation tensile-strength statistics, which Section 2.4 promises.

Section 2.4 states that "the mean tensile strength, standard deviation, and
coefficient of variation are reported for each orientation". They were not.
Figure 2 carries the per-angle means with their standard errors, Table 1 gives
overall means, and the coefficient of variation appeared once, at 75 degrees,
in Section 4.1. A reader wanting the per-angle dispersion had no table to go
to, and the retained specimen count per orientation was stated only as a range.

This writes that table from the replicate file, so the promise is kept from
the same source every other statistic is computed from.

    python scripts/make_strength_by_angle_table.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from tools import output_dirs                      # noqa: E402

RAW = REPO / "selected_all_samples.csv"
COL = "Tensile_strength_Mpa"


def statistics() -> pd.DataFrame:
    """Count, mean, standard deviation, standard error and CV, per angle."""
    d = pd.read_csv(RAW)
    g = d.groupby(["Rock_type", "Angle"])[COL]
    out = g.agg(n="count", mean="mean", sd="std").reset_index()
    out["sem"] = out["sd"] / out["n"] ** 0.5
    out["cv_pct"] = 100.0 * out["sd"] / out["mean"]
    return out.rename(columns={"Rock_type": "rock", "Angle": "angle_deg"})


def latex_table(t: pd.DataFrame) -> str:
    rows = []
    for rock in ("Psammitic schist", "Augen gneiss"):
        sub = t[t.rock == rock].sort_values("angle_deg")
        rows.append(rf"\multicolumn{{6}}{{l}}{{\textit{{{rock}}}}} \\")
        for r in sub.itertuples():
            rows.append(f"{r.angle_deg:.0f} & {r.n:.0f} & {r.mean:.2f} & "
                        f"{r.sd:.2f} & {r.sem:.2f} & {r.cv_pct:.1f} \\\\")
    body = "\n".join(rows)
    return rf"""% Generated by scripts/make_strength_by_angle_table.py; do not edit by hand.
\begin{{table}}[htbp]
\centering
\small
\caption{{\rev{{Brazilian tensile strength by fabric orientation, from the
retained specimens of each lithology. $n$ is the number of valid tensile
failures at that orientation, $\sigma_t$ their mean, and $s$, $s/\sqrt{{n}}$ and
$\mathrm{{CV}}$ the sample standard deviation, standard error and coefficient
of variation. These are the per-angle statistics the strength envelope is
weighted by and that Fig.~\ref{{fig:bts_model_fit}} plots as mean $\pm$ SEM.
Scatter is largest at $75^\circ$ in both rocks, the orientation at which each
is weakest.}}}}
\label{{tab:strength_by_angle}}
\begin{{tabular}}{{r r r r r r}}
\toprule
$\alpha$ (deg) & $n$ & $\sigma_t$ (MPa) & $s$ (MPa) & $s/\sqrt{{n}}$ (MPa) &
$\mathrm{{CV}}$ (\%) \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{table}}
"""


def main() -> int:
    t = statistics()
    output_dirs.tables()
    out_csv = Path(output_dirs.tables()) / "strength_by_angle.csv"
    t.to_csv(out_csv, index=False)
    out_tex = REPO / "manuscript/tables/table_S_strength_by_angle.txt"
    out_tex.write_text(latex_table(t), encoding="utf-8")

    for rock, g in t.groupby("rock"):
        worst = g.loc[g.cv_pct.idxmax()]
        print(f"  {rock:17s} n {int(g.n.min())}-{int(g.n.max())} per angle, "
              f"{int(g.n.sum())} total;  largest CV {worst.cv_pct:.1f}% at "
              f"{worst.angle_deg:.0f} deg")
    print(f"  wrote {out_csv.relative_to(REPO)}")
    print(f"  wrote {out_tex.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
