#!/usr/bin/env python3
"""Bound what the homogeneous elastic field neglects by not resolving the augen.

Produces the supplementary figure and table that quantify the local stress
fluctuation around a stiff inclusion, and the amount of stiffening a
whole-specimen modulus measurement already contains. The remote stress is taken
from the computed disk field rather than assumed, so the bound is stated for the
loading the specimens actually saw.

    python scripts/make_eshelby_supplement.py
"""
from __future__ import annotations

from pathlib import Path
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from tools import eshelby_bound as eb                # noqa: E402
from tools import output_dirs  # noqa: E402
from tools import fabric_tractions as ft             # noqa: E402
from tools.plot_style import apply_plot_style        # noqa: E402

REPO = Path(__file__).resolve().parents[1]

# Neither phase moduli nor augen shape were measured on these specimens, so both
# are swept over ranges wide enough to bracket a feldspar-quartz aggregate in a
# micaceous matrix. Nothing below is presented as a measured property.
E_MATRIX_GPA = 30.0
NU = 0.25
CONTRASTS = np.array([1.5, 2.0, 2.5, 3.0])
ASPECTS = np.array([1.0, 2.0, 3.0])
FRACTIONS = np.array([0.10, 0.20, 0.30, 0.40])


def remote_stress_from_field():
    """Mean stress in the gneiss disc core, as the remote state for the estimate."""
    for p in ft.field_files():
        f = ft.load_field(p)
        if f["rock"] == "Augen gneiss" and abs(f["angle_deg"]) < 1e-9:
            m = ft.core_mask(f)
            return np.array([float(np.mean(f["sxx"][m])),
                             float(np.mean(f["syy"][m])),
                             float(np.mean(f["txy"][m]))], float)
    raise SystemExit("gneiss 0 degree field not found; run the notebooks first")


def main():
    apply_plot_style()
    s_inf = remote_stress_from_field()
    Em = E_MATRIX_GPA * 1e3
    print(f"  remote stress from the gneiss disc core: "
          f"sxx={s_inf[0]:.2f}, syy={s_inf[1]:.2f}, txy={s_inf[2]:.2f} MPa")

    tab = eb.bound_table(Em, NU, NU, CONTRASTS, ASPECTS, s_inf)

    # how much stiffening a whole-specimen measurement already contains
    mt = []
    for c in CONTRASTS:
        for f in FRACTIONS:
            C = eb.mori_tanaka_modulus(Em, NU, Em * c, NU, 1.0, f)
            C0 = eb.stiffness_plane_strain(Em, NU)
            mt.append(dict(contrast=float(c), fraction=float(f),
                           stiffening=float(C[0, 0] / C0[0, 0])))
    mt = pd.DataFrame(mt)

    output_dirs.tables()
    tab.to_csv(REPO / output_dirs.TABLE_DIR / "eshelby_bound.csv", index=False)
    mt.to_csv(REPO / output_dirs.TABLE_DIR / "eshelby_mori_tanaka.csv", index=False)

    fig, ax = plt.subplots(1, 2, figsize=(7.6, 3.7))
    for a in ASPECTS:
        g = tab[tab.aspect == a]
        ax[0].plot(g.contrast, g.concentration, "-o", ms=5, lw=1.8,
                   label=f"axial ratio {a:.0f}:1")
    ax[0].axhline(1.0, color="0.4", ls=":", lw=1.2)
    ax[0].set_xlabel(r"Modulus contrast, $E_i/E_m$")
    ax[0].set_ylabel("Stress concentration")
    ax[0].legend(frameon=True)

    for c in CONTRASTS:
        g = mt[mt.contrast == c]
        ax[1].plot(g.fraction, g.stiffening, "-o", ms=5, lw=1.8,
                   label=rf"$E_i/E_m$ = {c:.1f}")
    ax[1].set_xlabel("Inclusion volume fraction")
    ax[1].set_ylabel("Effective stiffening")
    ax[1].legend(frameon=True)

    for a in ax:
        a.grid(True, alpha=0.3)
        for sp in a.spines.values():
            sp.set_linewidth(1.5)
    fig.tight_layout()
    for stem in (REPO / "manuscript/fig_S_eshelby_bound",
                 REPO / output_dirs.FIGURE_DIR / "fig_S_eshelby_bound"):
        fig.savefig(f"{stem}.pdf", dpi=300, bbox_inches="tight")
    plt.close(fig)

    cmax = tab.concentration.max()
    ar_max = float(tab.loc[tab.concentration.idxmax(), "aspect"])
    rigid = {a: eb.concentration_factor(Em, NU, Em * 1e8, NU, a, s_inf) for a in ASPECTS}
    nu_alt = 0.26
    alt = eb.bound_table(Em, nu_alt, nu_alt, CONTRASTS, ASPECTS, s_inf).concentration.max()
    rows = "\n".join(
        f"{r.contrast:.1f} & {r.aspect:.0f}:1 & {r.E_inclusion_GPa:.0f} & {r.concentration:.2f} \\\\"
        for r in tab.itertuples())
    (REPO / "manuscript/tables/table_S_eshelby_bound.txt").write_text(
        r"""% Generated by scripts/make_eshelby_supplement.py -- do not edit by hand.
\begin{table}[htbp]
\centering
\small
\caption{\rev{Bound on the stress fluctuation neglected by treating the augen gneiss as
elastically homogeneous. Each row gives the uniform stress inside a single elliptical
inclusion, from Eshelby's equivalent-inclusion solution \citep{Eshelby1957}, relative to
the remote stress,
for the mean stress state computed at the center of the $0^\circ$ gneiss disc. Phase
moduli and inclusion shape were not measured on these specimens, so the matrix modulus
is fixed at """ + f"{E_MATRIX_GPA:.0f}" + r"""~GPa and the contrast and axial ratio are swept over ranges
that bracket a feldspar--quartz aggregate in a micaceous matrix; the entries are
therefore a bound, not a property of the rock. The largest concentration over the whole sweep is
""" + f"{cmax:.2f}" + r""", reached by the most elongate and stiffest inclusion considered.
Each entry lies below the rigid-inclusion limit for its own shape, which the same
solution gives as """ + ", ".join(rf"${rigid[a]:.2f}$ at ${a:.0f}\!:\!1$" for a in ASPECTS) + r"""
at $\nu = 0.25$; elongation raises both the concentration and the limit it approaches,
so the circular value of $1.50$ bounds only the circular case. The estimate is
insensitive to the matrix Poisson ratio: repeating the sweep at the value measured on
the $0^\circ$ specimen, $\nu = """ + f"{nu_alt:.2f}" + r"""$, changes the largest
concentration to """ + f"{alt:.2f}" + r""".}}
\label{tab:eshelby_bound}
\begin{tabular}{r c r r}
\toprule
$E_i/E_m$ & Axial ratio & $E_i$ (GPa) & Concentration \\
\midrule
""" + rows + r"""
\bottomrule
\end{tabular}
\end{table}
""", encoding="utf-8")

    print(f"\n  concentration factors: {tab.concentration.min():.2f} to {cmax:.2f}")
    print(f"  perturbation falls below 10% beyond {eb.decay_radius(0.10):.2f} inclusion radii")
    print(f"  effective stiffening spans {mt.stiffening.min():.2f} to {mt.stiffening.max():.2f}")
    print("\n  written: fig_S_eshelby_bound.pdf, tables/table_S_eshelby_bound.txt, outputs/tables/*.csv")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
