#!/usr/bin/env python3
"""Supplementary evidence for the strength-envelope parameters.

Shows how the two fitted quantities are constrained. Each panel scans one
parameter while re-optimizing the other, so the width of the curve at
Delta chi-square = 3.84 is the 95% interval reported in the text. A parameter
whose scan has no interior minimum is not determined by the data, and this
figure is what makes that visible rather than asserted.

    python scripts/make_ati_supplement.py
"""
from __future__ import annotations

from pathlib import Path
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from tools import ati_model as A                      # noqa: E402
from tools import output_dirs                          # noqa: E402
from tools.data_io import load_replicate_table        # noqa: E402
from tools.plot_style import (apply_plot_style, ANNOT_FS,
                              LEGEND_FS, PANEL_LABEL_FS)         # noqa: E402

REPO = Path(__file__).resolve().parents[1]
COLOR = {"Augen gneiss": "#4C72B0", "Psammitic schist": "#DD4B39"}


def latex_table(rows) -> str:
    body = "\n".join(
        f"{r['rock']} & {r['sigma0']:.2f} & {r['sigma90']:.2f} & "
        f"{r['eta']:.3f} & [{r['eta_lo']:.2f}, {r['eta_hi']:.2f}] & "
        f"{r['beta_peak_deg']:.1f} & [{r['beta_lo']:.0f}, {r['beta_hi']:.0f}] & "
        f"{r['max_weakening_pct']:.1f} & {r['R2']:.3f} & {r['chi2_red']:.2f} \\\\"
        for r in rows)
    return rf"""% Generated by scripts/make_ati_supplement.py; do not edit by hand.
\begin{{table}}[htbp]
\centering
\small
\caption{{\rev{{Strength-envelope parameters. The end-member strengths
$\sigma_0$ and $\sigma_{{90}}$ are measured, not fitted, so only the depth
$\eta$ and the position $\beta_p$ of the weakening are estimated. Intervals are
95\% profile-likelihood ranges obtained by scanning one parameter while
re-optimizing the other. The envelope is additionally required not to predict a
strength below the lowest specimen broken in that lithology.}}}}
\label{{tab:ati_envelope}}
\begin{{tabular}}{{l r r r c r c r r r}}
\toprule
Lithology & $\sigma_0$ & $\sigma_{{90}}$ & $\eta$ & 95\% CI & $\beta_p$ &
95\% CI & $W$ drop & $R^2$ & $\chi^2_{{\mathrm{{red}}}}$ \\
 & (MPa) & (MPa) & & & (deg) & (deg) & (\%) & & \\
\midrule
{body}
\bottomrule
\end{{tabular}}
\end{{table}}
"""


def main():
    output_dirs.ensure()
    d = load_replicate_table()
    apply_plot_style()
    fig, axes = plt.subplots(1, 2, figsize=(7.4, 3.4))

    rows = []
    for rock in ("Psammitic schist", "Augen gneiss"):
        sub = d[d.Rock_type == rock]
        r = A.fit(sub)
        e_lo, e_hi, eg, ev = A.profile_interval(r, "eta", 0.0, 6.0, 0.05)
        b_lo, b_hi, bg, bv = A.profile_interval(r, "beta_peak", 45.0, 89.0, 1.0)
        r.update(rock=rock, eta_lo=e_lo, eta_hi=e_hi, beta_lo=b_lo, beta_hi=b_hi)
        rows.append({k: v for k, v in r.items() if not k.startswith("_")})

        for ax, g, v, best, lo, hi in ((axes[0], eg, ev, r["eta"], e_lo, e_hi),
                                       (axes[1], bg, bv, r["beta_peak_deg"], b_lo, b_hi)):
            ax.plot(g, v - v.min(), color=COLOR[rock], lw=2.0, label=rock)
            ax.axvspan(lo, hi, color=COLOR[rock], alpha=0.10, lw=0)
            ax.axvline(best, color=COLOR[rock], ls="--", lw=1.0, alpha=0.7)

    for ax, xlabel in ((axes[0], r"weakening depth $\eta$"),
                       (axes[1], r"weakening position $\beta_p$ (deg)")):
        ax.axhline(A.DELTA_CHI2_95, color="0.35", ls=":", lw=1.2)
        ax.text(0.98, A.DELTA_CHI2_95, r"95\%", transform=ax.get_yaxis_transform(),
                ha="right", va="bottom", fontsize=ANNOT_FS, color="0.35")
        ax.set_xlabel(xlabel)
        ax.set_ylim(0, 12)
        ax.grid(True, alpha=0.3)
        for s in ax.spines.values():
            s.set_linewidth(1.5)
    axes[0].set_ylabel(r"$\Delta\chi^2$ from the optimum")
    # One shared legend below the figure. Inside the right panel it sat over
    # the profile it was labelling; both panels carry the same two curves.
    handles, labels = axes[1].get_legend_handles_labels()
    fig.tight_layout(rect=(0, 0.08, 1, 1))
    fig.legend(handles, labels, loc="lower center", ncol=len(labels) or 2,
               frameon=False, fontsize=LEGEND_FS, bbox_to_anchor=(0.5, -0.01))
    out = REPO / "manuscript/fig_S_ati_profiles"
    for ext in ("pdf", "png"):
        fig.savefig(f"{out}.{ext}", dpi=300, bbox_inches="tight")
    plt.close(fig)

    df = pd.DataFrame(rows)
    df.to_csv(REPO / output_dirs.TABLE_DIR / "ati_envelope_parameters.csv", index=False)
    (REPO / "manuscript/tables/table_S_ati_envelope.txt").write_text(
        latex_table(rows), encoding="utf-8")

    for r in rows:
        print(f"  {r['rock']:17s} eta={r['eta']:.3f} [{r['eta_lo']:.2f},{r['eta_hi']:.2f}]"
              f"  beta_p={r['beta_peak_deg']:.1f} [{r['beta_lo']:.0f},{r['beta_hi']:.0f}]"
              f"  R2={r['R2']:.3f}  chi2red={r['chi2_red']:.2f}")
    print("\nwritten: manuscript/fig_S_ati_profiles.pdf, manuscript/tables/table_S_ati_envelope.txt,")
    print("         outputs/tables/ati_envelope_parameters.csv")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
