#!/usr/bin/env python3
"""Emit the two supplement tables that had drifted from their datasets.

Table B.12 (fracture-trace orientations) and Table B.13 (energy connectivity)
were maintained by hand, and B.13's source file had lost its producer entirely,
so both carried values from superseded runs. They are written here from the
same functions the analysis uses, into ``manuscript/tables/*.txt``, which
``scripts/inline_tables.py`` then splices into the manuscript.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from tools import energy_localization as elz   # noqa: E402
from tools import traces as tr                 # noqa: E402

TABLE_DIR = REPO / "manuscript" / "tables"


def trace_validation_body() -> str:
    rows = tr.compare_all()
    null = tr.null_model_statistics(rows)
    prim, lines = [], []
    for r in rows:
        p = r["abs_axial_angular_error_deg"]
        prim.append(p)
        lines.append(
            f"{r['sample']} & {r['lithology']} & "
            f"{r['experimental_angle_deg']:.0f} & "
            f"{r['observed_orientation_deg']:.1f} & "
            f"{r['observed_bootstrap_sd_deg']:.1f} & "
            f"{r['predicted_orientation_deg']:.1f} & "
            f"{r['observed_n_segments']} & {p:.1f} \\\\")
    P = np.array(prim)
    lines.append(r"\hline")
    for label, a in (
            ("Mean absolute error", P.mean()),
            ("Root-mean-square error", np.sqrt((P ** 2).mean())),
            ("Median absolute error", np.median(P)),
            ("Maximum absolute error", P.max()),
            ("Loading-parallel null, scored identically", null["mae_deg"])):
        lines.append(
            f"\\multicolumn{{7}}{{l}}{{{label}}} & {a:.1f} \\\\")
    return "\n".join(lines)


def energy_localization_body() -> str:
    t = elz.localization_table()
    # Schist first, matching the figure order used throughout.
    order = ["Psammitic schist", "Augen gneiss"]
    t = t.sort_values(
        ["rock", "angle_deg"],
        key=lambda c: c.map(order.index) if c.name == "rock" else c)
    lines = []
    for _, r in t.iterrows():
        lines.append(
            f"{r['rock']} & {r['angle_deg']:.0f} & {int(r['n_components'])} & "
            f"{r['largest_fraction']:.3f} & {r['elongation']:.2f} & "
            f"{'yes' if r['corridor'] else 'no'} \\\\")
    return "\n".join(lines)


CAP_TRACE = r"""\caption{\rev{Predicted versus observed primary fracture-trace orientations for all fourteen specimens. Orientations are axial, measured counterclockwise from the horizontal diameter ($+x$); the loading diameter lies at $90^\circ$. Both the digitized and the predicted trace are read over the same interior, $r \le 0.85R$, the domain over which every field diagnostic here is taken, and the primary fracture is identified from the complete digitized trace before clipping. $\sigma_{\mathrm{fit}}$ is the bootstrap standard deviation of the total-least-squares orientation fit (digitization and fit scatter; one specimen was tested per fabric angle, so no replicate scatter is measurable). $n_{\mathrm{seg}}$ is the number of connected cracks digitized on that specimen and $|\Delta\theta|$ is the axial error against the longest of them. Summary statistics are quoted in the main text.}}"""

CAP_ENERGY = r"""\caption{\rev{Connectivity and shape of the elevated strain-energy region, defined as the
upper quartile of strain-energy density inside $0.85R$. Components are labeled with
eight-fold connectivity; the largest fraction is the share of the elevated area in the
biggest component, and elongation is the square root of the ratio of its second moments,
unity for an equant patch. A corridor is recorded when the region forms a single component
with elongation of at least two. Two components is the unconnected baseline set by the two
platen lobes of diametral loading.}}"""

HEAD = "% Generated by scripts/make_trace_and_connectivity_tables.py; do not edit by hand."


def trace_validation_table() -> str:
    return "\n".join([
        HEAD,
        r"\begin{table}[htbp]", r"\centering", CAP_TRACE,
        r"\label{tab:trace_validation}",
        r"\begin{tabular}{rlrrrrrr}", r"\hline",
        r"Specimen & Lithology & $\alpha$ & $\theta_{\mathrm{obs}}$ & "
        r"$\sigma_{\mathrm{fit}}$ & $\theta_{\mathrm{pred}}$ & "
        r"$n_{\mathrm{seg}}$ & $|\Delta\theta|$ \\",
        r" & & (deg) & (deg) & (deg) & (deg) & & (deg) \\",
        r"\hline",
        trace_validation_body(),
        r"\hline", r"\end{tabular}", r"\end{table}",
    ])


def energy_localization_table() -> str:
    return "\n".join([
        HEAD,
        r"\begin{table}[htbp]", r"\centering", r"\small", CAP_ENERGY,
        r"\label{tab:energy_localization}",
        r"\begin{tabular}{l r r r r c}", r"\toprule",
        r"Lithology & $\alpha$ (deg) & Components & Largest fraction & "
        r"Elongation & Corridor \\",
        r"\midrule",
        energy_localization_body(),
        r"\bottomrule", r"\end{tabular}", r"\end{table}",
    ])


def main() -> int:
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    for name, body in (
            ("table_S_trace_validation", trace_validation_table()),
            ("table_S_energy_localization", energy_localization_table())):
        (TABLE_DIR / f"{name}.txt").write_text(body + "\n", encoding="utf-8")
        print(f"  written: {name}.txt")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
