"""Blocks a script rewrites must say so in the document.

``scripts/patch_stress_field_text.py`` regenerates four blocks on every run:
the displacement-field caption, the stress-direction caption, the
fabric-traction caption and the Section 4.5 traction paragraph. Nothing in the
document said so, and the consequence was not hypothetical. A hand edit to the
paragraph was reverted by the next run, and because the generator replaces only
up to the block's closing anchor, the remainder of the edit was left stranded
and ended in a brace with nothing to close. That compiled: the right page
count, no undefined references, a recoverable "Too many }'s" buried in the log.

Each block now carries the same ownership notice the supplementary tables get
from ``inline_tables.py``, so the warning is where an editor is looking.
"""
from __future__ import annotations

import hashlib
import re
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
TEX = REPO / "manuscript" / "manscript_revision_001.tex"
SCRIPT = REPO / "scripts" / "patch_stress_field_text.py"

MARK = ("% >>> GENERATED BY scripts/patch_stress_field_text.py "
        "-- edit that script, not this block <<<")

OWNED_HEADS = [
    r"\caption{\rev{Displacement fields for (a) psammitic schist",
    r"\caption{\rev{Principal stress directions for (a) psammitic schist",
    r"\caption{\rev{Tractions resolved on the foliation plane",
    r"\rev{Resolving the modeled stress state",
]

pytestmark = pytest.mark.skipif(not TEX.is_file(), reason="manuscript not present")


def test_every_owned_block_carries_the_notice():
    lines = TEX.read_text(encoding="utf-8").split("\n")
    for head in OWNED_HEADS:
        idx = [i for i, l in enumerate(lines) if l.lstrip().startswith(head.lstrip())]
        assert len(idx) == 1, f"expected one block starting {head!r}, found {len(idx)}"
        i = idx[0]
        assert i > 0 and lines[i - 1] == MARK, (
            f"the block starting {head!r} is regenerated by "
            "patch_stress_field_text.py but carries no ownership notice; an "
            "edit to it here would be silently reverted")


def test_the_notice_count_matches_the_owned_block_count():
    n = TEX.read_text(encoding="utf-8").count(MARK)
    assert n == len(OWNED_HEADS), (
        f"{n} ownership notices for {len(OWNED_HEADS)} owned blocks; a block "
        "has been added or removed without updating this test")


@pytest.mark.slow
def test_regenerating_changes_nothing():
    """Idempotence: a clean tree stays clean when the generator runs again.

    This is what makes a hand edit detectable. If someone edits an owned block
    in the .tex, this test fails on the next run because the generator rewrites
    it, which is the whole point of the notice above.
    """
    before = hashlib.md5(TEX.read_bytes()).hexdigest()
    r = subprocess.run([sys.executable, str(SCRIPT)], cwd=REPO,
                       capture_output=True, text=True)
    assert r.returncode == 0, r.stderr[-2000:]
    after = hashlib.md5(TEX.read_bytes()).hexdigest()
    assert before == after, (
        "running patch_stress_field_text.py changed the document. Either an "
        "owned block was edited by hand in the .tex, or the results tables "
        "changed and the document had not been regenerated from them.")
